server:
  port : 8090
   
spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: git-hub-client-id
            clientSecret: git-hub-client-secret
          google:
            client-id: google-client-id
            client-secret: google-client-secret-key